### PR TITLE
Fix some issues with string escaping/unescaping in the SMTLib2 writer

### LINKED ISSUE #184: String solver values when using Z3
Hello,

when I use What4 with Z3 and try to generate single characters using the built-in string support, I have some trouble. In particular, What4 seems unable to parse the `\` character in the solver solution as the following error message indicates.
```
*** Exception: user error (Could not parse string solver value:
  SString "\\")
```
Furthermore, it seems as if What4 using Z3 only generates 96 characters in total (can be tested if you exclude the problematic `\` character; then you get the remaining 95 solutions).

Cheers,
Finn

PS: For reference, I give my test module below.
```haskell
{-# LANGUAGE LambdaCase          #-}
{-# LANGUAGE ScopedTypeVariables #-}

module What4Test where

import Data.Data
import Data.Parameterized
import Data.Parameterized.Nonce
import Data.Text

import System.IO.Unsafe

import What4.Config
import What4.Expr
import What4.Interface
import What4.Protocol.Online
import What4.Protocol.SMTLib2
import What4.Solver
import What4.Utils.StringLiteral

getChars :: [Char]
getChars = unsafePerformIO $ do
    Some (ng :: NonceGenerator IO x) <- newIONonceGenerator
    sym <- newExprBuilder FloatIEEERepr Proxy ng
    extendConfig z3Options (getConfiguration sym)
    solver <- startSolverProcess z3Features Nothing sym :: IO (SolverProcess x (Writer Z3))
    let conn = solverConn solver
    -- Create string var and constrain its length to 1
    x <- freshConstant sym (safeSymbol "x") (BaseStringRepr UnicodeRepr)
    l <- stringLength sym x
    intLit sym 1 >>= isEq sym l >>= assume conn
    -- Recursively generate characters
    let getModelsRecursive =
          runCheckSat (Session conn (solverResponse solver)) $ \case
            Sat (ge, _) -> do
              v <- groundEval ge x
              -- Exclude value
              stringLit sym v >>= isEq sym x >>= notPred sym >>= assume conn
              return $ (Data.Text.head . fromUnicodeLit) v : unsafePerformIO getModelsRecursive
            _           -> shutdownSolverProcess solver >> return []
    getModelsRecursive
```

### LINKED ISSUE #185: Extended/unprintable characters when using CVC4
Hello (again),

when I use What4 with CVC4 and try to generate single characters using the built-in string support, it seems as if extended/unprintable characters are not correctly handled as the following error message indicates.
```
*** Exception: Solver reported an error:
  Parse Error: <stdin>:652.37: Extended/unprintable characters are not part of SMT-LIB, and they must be encoded as escape sequences
in response to command:
  (define-fun x!259 () Bool (= x!0 " "))
```

Cheers,
Finn

PS: For reference, I give my test module below.

```haskell
{-# LANGUAGE LambdaCase          #-}
{-# LANGUAGE ScopedTypeVariables #-}

module What4Test where

import Data.Data
import Data.Parameterized
import Data.Parameterized.Nonce
import Data.Text

import System.IO.Unsafe

import What4.Config
import What4.Expr
import What4.Interface
import What4.Protocol.Online
import What4.Protocol.SMTLib2
import What4.Solver
import What4.Utils.StringLiteral

getChars :: [Char]
getChars = unsafePerformIO $ do
    Some (ng :: NonceGenerator IO x) <- newIONonceGenerator
    sym <- newExprBuilder FloatIEEERepr Proxy ng
    extendConfig cvc4Options (getConfiguration sym)
    solver <- startSolverProcess cvc4Features Nothing sym :: IO (SolverProcess x (Writer CVC4))
    let conn = solverConn solver
    -- Create string var and constrain its length to 1
    x <- freshConstant sym (safeSymbol "x") (BaseStringRepr UnicodeRepr)
    l <- stringLength sym x
    intLit sym 1 >>= isEq sym l >>= assume conn
    -- Recursively generate characters
    let getModelsRecursive =
          runCheckSat (Session conn (solverResponse solver)) $ \case
            Sat (ge, _) -> do
              v <- groundEval ge x
              -- Exclude value
              stringLit sym v >>= isEq sym x >>= notPred sym >>= assume conn
              return $ (Data.Text.head . fromUnicodeLit) v : unsafePerformIO getModelsRecursive
            _           -> shutdownSolverProcess solver >> return []
    getModelsRecursive
```

### PR DESCRIPTION
**Pull request by robdockins**
Previously, we were too liberal with the characters we would emit
without escaping, and we would incorrectly fail to escape `\` characters
if they had a following `u` character.  In addition, our unescaping routine
was incorrectly rejecting strings from solvers if they ended with a literal
`\` character.

Fixes #184
Fixes #185

### CODE REVIEW

**Comment by robdockins** [comment]
@finnteegen, I think this PR fixes the issues you encountered with the string theory.  Do you have any objection if I tweak your examples and add them to our test suite?

File: what4/test/ExprBuilderSMTLib2.hs [hunk 1]
```diff
@@ -922,6 +922,62 @@ stringTest5 sym solver = withChecklist "string5" $
        _ -> fail "expected satisfable model"
 
 
+stringTest6 ::
```
Comment (RyanGlScott) [inline what4/test/ExprBuilderSMTLib2.hs:925]: A comment here describing what property this is testing would be helpful, since the name `stringTest6` alone doesn't say much on its own.

File: what4/test/ExprBuilderSMTLib2.hs [hunk 2]
```diff
@@ -922,6 +922,62 @@ stringTest5 sym solver = withChecklist "string5" $
...
+     l <- stringLength sym x
+     intLit sym 1 >>= isEq sym l >>= assume conn
+     stringLit sym (UnicodeLiteral (Text.pack "\\")) >>= isEq sym x >>= assume conn
+     checkAndGetModel solver "test" >>= \case
+       Sat ge -> do
+         v <- groundEval ge x
+         TC.check "correct string" (v ==) (UnicodeLiteral (Text.pack "\\"))
+       _ -> fail "unsatisfiable"
+
+stringTest7 ::
```
Comment (RyanGlScott) [inline what4/test/ExprBuilderSMTLib2.hs:942]: Similarly, leave a comment here describing what this tests.

**Review by RyanGlScott — APPROVED** [review]

**Comment by robdockins** [comment]
CI failures all appear to be due to #189
